# Generated by Django 4.0.4 on 2022-06-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=5)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('vid', models.CharField(max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('tags', models.BooleanField(default=False)),
                ('url', models.URLField(default='')),
                ('comments', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
