# Generated by Django 4.0.4 on 2022-05-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('long_desc', models.CharField(max_length=200)),
                ('img', models.FileField(null=True, upload_to='images/', verbose_name='')),
                ('vid', models.FileField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
    ]
