# Generated by Django 4.0.4 on 2022-06-29 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_feed1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed1',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='feed1',
            name='url',
        ),
    ]
