# Generated by Django 4.0.4 on 2022-05-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_feed_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='vid',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
