# Generated by Django 4.0.4 on 2022-05-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_feed_img_alter_feed_vid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='long_desc',
        ),
        migrations.AddField(
            model_name='feed',
            name='tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feed',
            name='img',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feed',
            name='vid',
            field=models.CharField(max_length=100),
        ),
    ]
