# Generated by Django 4.0.4 on 2022-05-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_delete_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='long_desc',
        ),
        migrations.AddField(
            model_name='feed',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='feed',
            name='comments',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='feed',
            name='tags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feed',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='feed',
            name='img',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feed',
            name='vid',
            field=models.CharField(max_length=100),
        ),
    ]
