# Generated by Django 4.0.4 on 2022-05-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_feed_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='comments',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='feed',
            name='urls',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
